[[services]]
id = "backend"
source = "./backend"
builder = "NIXPACKS"
buildCommand = "npm install"
startCommand = "npm start"

[[services]]
id = "frontend"
source = "./frontend"
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npm run preview"
staticUrl = "/"

[[databases]]
id = "postgres"
database = "wanderlust"